api: add missing tests dependency for BSDs after e2bf7b278d17
test/misc/safe-list-test.cpp:2:10: fatal error: 'doctest/doctest.h' file not found
 #include <doctest/doctest.h>
          ^~~~~~~~~~~~~~~~~~~